### ISSUE TITLE
Add /tempban and /ban commands

### ISSUE THREAD

**Issue by Legoman99573** [garagepoort/StaffPlusPlus#106]
I noticed these two were missing and was wondering if you are willing to add these in at anytime?

**Comment by garagepoort** [comment]
Hi Legoman,

Yes I would be willing to add those. Temp ban could be very useful.
Will try to add it in version 1.16.27

**Comment by Azoraqua** [comment]
To me, it doesn't make much sense to add any banning functionality. As to me Staff+(+) is intended to be a support tool and not necessarily a moderation suite.

@garagepoort @Legoman99573

**Comment by garagepoort** [comment]
@Azoraqua  Wasn't that line crossed already when warning and reports were added?

**Comment by Azoraqua** [comment]
It is and it is not. Warnings and especially reports are more regarding support for staff than axtual moderation tools.

**Comment by garagepoort** [comment]
Reports I could see as being a support feature but warnings seems to lean more to moderation imo.
Anyway I added the ban feature in the next release as I would want to take Staff++ further than just a support plugin.
