### ISSUE TITLE
[Bug] Cannot ban a player who is offline

### ISSUE THREAD

**Issue by Legoman99573** [garagepoort/StaffPlusPlus#115]
Even though the player has joined the server, it doesn't allow me to ban them unless they are online. Only outcome it gives me is that "This player does not exist."

**Comment by garagepoort** [comment]
Hi @Legoman99573
Just to be sure you did enable this option in the config? `offline-players-mode: true`

**Comment by Legoman99573** [comment]
Yeah, that worked. Probably didnt pay attention to that configuration option as i didnt touch that option.

**Comment by garagepoort** [comment]
> Yeah, that worked. Probably didnt pay attention to that configuration option as i didnt touch that option.

when I first implemented the offline users feature I added the configuration option to not break with the old Staff+ implementation. Maybe I should change it to be on by default? I will also update the wiki, I don't think it is documented now.
