### ISSUE TITLE
Warm in chest, no severity

### ISSUE THREAD

**Issue by DjTylerD** [garagepoort/StaffPlusPlus#123]
hello, I am currently setting up a server and I find your excellent plugin to facilitate my administrators.
  I discovered a small lack, in the trunk the warning does not give severity, could you measure at least 1 point.
(sorry for my english, i use google translate)

version: 1.16.33
![Capture d’écran 2020-11-14 192508](https://user-images.githubusercontent.com/35812264/99154641-c0c2f080-26b1-11eb-9a24-09a94cfc270b.png)

**Comment by garagepoort** [comment]
Hi @DjTylerD,

I think I understand what you mean. Warnings do indeed not get a severity when players are warned using the GUI.
I will fix it

**Comment by DjTylerD** [comment]
Thank you for the quick reply

**Comment by garagepoort** [comment]
@DjTylerD A way to bypass this bug is to use the warn command rather than the GUI

**Comment by DjTylerD** [comment]
yes I know,
but my moderator will have a new toy, so will necessarily test, and all my administration system is not in chat control,
I force them to go through tigerReport because there is no command, ban, kick ect,
conclusion I deactivate on your pluggin report I want to keep the warm and change the line:
actions:
         - command: ban% player% & 4Warning threshold has been met
en - command: reportplayer% player% & 4Staff ++ warnings reported
I tested in manual warm and the 2 pluging works well

**Comment by garagepoort** [comment]
Ok I understand. Will fix it in next release

**Comment by DjTylerD** [comment]
you have time,
in any case very good plugin, felicitation,
I'm testing it in pv but I'm sure the moderators will be appreciated,
I link it with all my pluggin, because as I said there is no important command all this goes through the console

**Comment by garagepoort** [comment]
Fixed in commit: https://github.com/garagepoort/StaffPlusPlus/commit/077b39919c959288e67123b0e4e9086e9aae85be
Will be included in the next release

**Comment by garagepoort** [comment]
@DjTylerD New version release. Let me know if this fixes your issue

**Comment by DjTylerD** [comment]
thank you, I install it and I will come back to you on another topic after testing because I have error messages on the clear command and the multi-ip function

**Comment by DjTylerD** [comment]
excellent, very good work, the 3 type of warn in the mistletoe, I close the topic
