### ISSUE TITLE
[feature request] report investigation mode

### ISSUE THREAD

**Issue by heathfx** [garagepoort/StaffPlusPlus#131]
one thing I currently do is limit the permissions of my staff until they are in staff mode, so they can't teleport, can't use core protect and can't access the inventoryRollback plugin until they activate staff mode.

There is a great opportunity to take this a step further by limiting staff permissions until they are "investigating" an open report. What this "investigation mode" would do is set permissions that would enable rollbacks, etc., but better yet save an audit log of the commands a staff member runs while working on a specific report. when they run any command or use staff chat while investigating a report, that command or chat and their XYZ coords in game will be logged alongside that report.

this would be a great way to prevent staff abuse.

**Comment by garagepoort** [comment]
This is an interesting idea. I think having an audit log could be very useful.
I'm only wondering when to turn it on and off. Because I can imagine someone picks up a report but then suddenly has to wait for feedback or something and the report stays assigned to them. In this "waiting" period we won't want to do audit logging.

Maybe I should add a status "blocked", so staff members can temporarily block them and the audit log will stop.

**Comment by heathfx** [comment]
I think the "ASSIGNED" state should be independent from and "investigation mode".

in the same sense that we have "staff mode" where the staff member has total vanish and can fly around, I would envision another mode that (in how I intend to use it) acts as a child mode of "staff mode", so to access "investigation mode", one must first be in "staff mode".

The following events would automatically disable "investigation mode":
* Disconnecting from the server
* Exiting "staff mode"
* Marking a report as resolved or dismissed (closing the report)
* Un-assigning the report

Maybe to add additional prompts that "investigation mode" is active, a bossbar is shown to serve as a constant reminder of the name of the player whose report you are currently investigating and being audited for.

"investigation mode" can only be activated from the page of an assigned report, meaning that a staff member would have to explicitly enable the mode. In my use case, I would require investigation mode to be active for the staff member to be given permissions to access rollback commands. To do this I would simply add some command hooks to run a luckperms command to add the staff member to a permission group upon investigation mode activated and then another command to remove them from the group once investigation mode is de-activated.

**Comment by garagepoort** [comment]
Ok I see, I will need some time to investigate how easy it would be to fit in such a system and to see if other users might also find this a useful feature.

But I really like the idea. Give me some time to come up with the implementation.
