### ISSUE TITLE
[feature request] points-based reputation and punishments

### ISSUE THREAD

**Issue by heathfx** [garagepoort/StaffPlusPlus#133]
Something I plan to do on my server when 1.17 comes out is to implement a new points-based player reputation system that keeps n00bs on a tight leash, but makes it so long-time players don't get perma-banned as easily.

This is a feature I want bad enough that I intend to fork BanManager and write it myself if I can't find another solution, but I thought it would be worth sharing here since you are trying to revive staff+. This could be a feature that would set it apart from others.

Here is how the reputation system would work, keep in mind that the time periods and points values would all be configurable.

1. A brand new player is assigned a reputation score of 3 when they first join.
2. A player earns points by logging in at least once every month and after 90 days they will be awarded 1 reputation point and this repeats until the player accumulates a maximum of 10 points. If they fail to join the server for a month then the 90 day timer will reset next time they join.
3. A player will lose 1 point for warnings or mutes. They will lose 2 points for suspensions/tempbans.
4. If their reputation drops to 0 they will be perma-banned without the ability to appeal.

A punishment rollback feature is a must-have that automatically restores points if the punishment is successfully appealed.

A hook system that allows commands to be run when a punishment is given and commands that run when the punishment expires or is rolled back.

If punishments are tied to report investigations as described in feature request #131, then it will be important to make sure the the status of a report is changed from "resolved" to "dismissed" if the related punishment is rolled back. For this to work seamlessly I would make it so a staff member can only deal punishments while in "investigation mode". If there is no report, but a staff member observes someone breaking the rules, then that staff member can create a new report with /reportplayer that instantly assigns the report to themselves and enters investigation mode for that report. If they need to perform some sort of "emergency stop" on a player, I would use the freeze command for this and hook a command to it that mutes the player if frozen and sets permissions that sync to discord to mute them there as well.

**Comment by garagepoort** [comment]
Ok so if I would develop it I would release it as a standalone plugin tbh. Because keeping a reputation system if more so for the players than it is for staff. Staff++ mostly focuses on player administration.

But what I could do is make Staff++ more flexible so it's easy to hook in such a system. For example add command hooks on report state changes. I already have hooks for warnings.

**Comment by heathfx** [comment]
I mean it could be considered "out of scope" for this plugin, but you already have something like this in the much more basic form of counting warnings and allowing a threshold number of warnings to automatically ban someone. I like reports being part of this plugin, but honestly any form of a punishment system might be out of scope.

On my server I use staff++ strictly as a tool to handle investigative functions (observing players, staff chat, reports and enabling permissions to use coreprotect only while staff mode is active) while I use a separate plugin to handle punishments.

More hooks would be nice, so instead of adding a bunch of internal modules which always run the risk of turning a plugin into something really bloaty (cough cough...EssentialsX) you could have a collection of plugins that allow people to pick only the ones they need.

For me the points system really is for staff, it gives us a way to show a little more mercy to veteran players while being more strict with n00bs that come in just wanting to wreck everything. It helps to make sure that players are treated more consistently when interacting with different staff members.

It would double as a way to motivate players to be good, if you make their reputation score public through 3rd party plugins with the use of PlaceholderAPI.

Ultimately I think the potential for this would be a lot more powerful if it was integrated with reporting and punishments and making sure that there is an all-important rollback system to restore points, unban and dismiss related reports all in one seamless action.

I feel really confident in my vision for this idea, so for now, I'll fork this and work on my own feature branch and submit a pull request when I think I have something workable, then you can decide if you want to pull it and have it serve as an internal module or if it would be better off as a standalone plugin.

**Comment by heathfx** [comment]
I'm going to implement this as a plugin for BanManager, I think it will fit better within "scope" of BanManager.

Sidenote: I previously used BM for reports, but staff++ actually has a better report system, where BM lacks an option to report without specifying a player name. The discord integration with webhooks is nice as well.

I prefer using an ORM like ORMlite for database interaction since it provides a wider range of database support and removes the need to write my own SQL queries. Since BanManager already uses ORMlite, it will be more comfortable/familiar to work with.

**Comment by garagepoort** [comment]
Hey @heathfx

I am still thinking about your reputation system. I don't know if I will have the time to create a plugin like that soon but if I do it will be a standalone one which easily integrates with Staff++.

The choice for not having an ORM was mainly because Staff+ wasn't using one so I kind of kept on building on what they had.
Although in retrospect I threw out 90% of Staff+ database integration so I might as well had start over new.
