### ISSUE TITLE
[bug] vanish state desync from staff mode

### ISSUE THREAD

**Issue by heathfx** [garagepoort/StaffPlusPlus#137]
**the problem**
stuck in vanish mode and toggling staff mode does not resolve.

also running the command "/vanish \<username\> disable" fails with the error of user not found

**to reproduce**
shutdown the server while a staff member is connected and in staff mode

**my workaround**
manually edit data.yml to set the vanish mode to NONE and restart the server

**Comment by garagepoort** [comment]
@heathfx 
I'll look into why the state gets desynced.
The command to turn vanish of is: `/vanish TOTAL <username> disable`

**Comment by heathfx** [comment]
I tried that too and still got a user not found error. I even copied and pasted the username to make sure I wasn't mis-typing.

**Comment by garagepoort** [comment]
Hey @heathfx 
Are you executing the command as op? And also make sure no other plugin like essentials is overwriting the command.
I haven't reworked this part of the code yet. I'll probably do that soon to make it more user friendly.

**Comment by heathfx** [comment]
yea it was from the shell/console...so, definitely op

I have essentials. but I edited the plugin.yml to remove everything I didn't user because I had so many issues with it conflicting with commands provided by "better" plugins. essentials is so bloated I'm working on getting rid of it and replacing it with more concise plugins.

**Comment by garagepoort** [comment]
hey @heathfx 
Do you still have this problem?

**Comment by garagepoort** [comment]
Closed due to inactivity
