### ISSUE TITLE
[feature request] add coordinates to reports

### ISSUE THREAD

**Issue by heathfx** [garagepoort/StaffPlusPlus#139]
When a player runs /report or /reportplayer it is very important for staff to know where the report was submitted. in-game it would be good to have a teleport button inside of the report to teleport to where the report was logged.

the coords should be shown in the tooltip when you hover over the player head.

the discord webhooks messages should also include the coords.

**Comment by garagepoort** [comment]
Good suggestion will definitely try to add this in next release.

**Comment by heathfx** [comment]
sweet thanks!

**Comment by garagepoort** [comment]
Added in 1.16.48
