### ISSUE TITLE
sp_warnings.is_expired constraint violation

### ISSUE THREAD

**Issue by KayleePhoto** [garagepoort/StaffPlusPlus#144]
Not sure what causes this to appear, but every so often I get this warning in my console

`WARN Plugin StaffPlus v1.16.49 generated an exception while executing task 13320
INFO java.lang.RuntimeException: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: sp_warnings.is_expired)`

`Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: sp_warnings.is_expired)`

I changed it over to MySQL and I believe I have to restart the server for it to take affect, as the server is on a hosting website.
but currently, I do get that warning. I've been looking for the past hour trying to figure out what is causing it.
I understand it just a tiny bit, but not fully to where I could fix this on my own.

**Comment by garagepoort** [comment]
Ow that's not good. Which version of the plugin are you running? Could you give me the full stack trace?

**Comment by KayleePhoto** [comment]
Currently using 1.16.49
And I presume the stack trace is the full log output of it? I'm not too sure.

**Comment by garagepoort** [comment]
Can you update to 1.16.50. because that version fixes that bug iirc.

**Comment by KayleePhoto** [comment]
Alright, I updated, haven't gotten it yet.
I was thinking it was just the version. I'll update you after awhile if preferred.
If not, I see it as fixed

**Comment by garagepoort** [comment]
If it's fixed you can just let me know here. If not you can always contact me through discord as well.

**Comment by garagepoort** [comment]
Assuming this fixed it.
