### ISSUE TITLE
Server can't enable plugin after converting configuration

### ISSUE THREAD

**Issue by Bartek200219** [garagepoort/StaffPlusPlus#159]
Server can't enable plugin after converting configuration.
Server: paper-700 1.16.5
Error:
https://paste.ee/p/Ss5MX

**Comment by garagepoort** [comment]
Hey @Bartek200219 
Could you try enabling the investigations module to see if that fixes it?

**Comment by Bartek200219** [comment]
Hey, thanks for fast reply. I think my storage type is flatfile
`storage:
  type: flatfile
  mysql:
    host: localhost
    user: root
    database: root
    password: mypass
    port: 3306
    migrated: false`

**Comment by garagepoort** [comment]
Hey @Bartek200219 
Flatfile is not supported in staff++, please change it to `sqlite`

**Comment by garagepoort** [comment]
@Bartek200219 Has this been resolved?

**Comment by Bartek200219** [comment]
Yes, thank you.
