### ISSUE TITLE
/examine Interaction bug

### ISSUE THREAD

**Issue by Bartek200219** [garagepoort/StaffPlusPlus#160]
In player's inventory I can't move items in player's inventory, but I can grab items to my inventory then form my inventory I can put somewhere else in player's inventory.
![2021-05-30_23-34-56](https://user-images.githubusercontent.com/37016424/120120798-fc319200-c19f-11eb-889f-39ed3d3f7f54.gif)

**Comment by garagepoort** [comment]
Hi @Bartek200219 

This is actually a known limitation of the current implementation.
What you describe is indeed a work around for this limitation. Sorry about that
