### ISSUE TITLE
tempmute bug 

### ISSUE THREAD

**Issue by Bartek200219** [garagepoort/StaffPlusPlus#163]
![image](https://user-images.githubusercontent.com/37016424/121777854-6977f680-cb94-11eb-86a4-cad72b85aaf0.png)
Log: https://paste.ee/p/lXXRQ

**Comment by garagepoort** [comment]
@Bartek200219 Thank you for the bug report.
Will be fixed with next release

**Comment by garagepoort** [comment]
Fixed in 1.16.70
