### ISSUE TITLE
Staff++ shadows de.tr7zw.nbtapi without prefixing it

### ISSUE THREAD

**Issue by toddharrison** [garagepoort/StaffPlusPlus#165]
When starting CommandAPI and Staff++ at the same time, I get this error:
[21:16:36 WARN]: [CommandAPI] Loaded class de.tr7zw.nbtapi.NBTContainer from StaffPlus v1.17.4 which is not a depend, softdepend or loadbefore of this plugin.
This indicates that both Staff++ and CommandAPI are shadowing the nbtapi library without prefixing it to prevent overloading. Both libraries should prefix the shadowed library in case they require different versions.

**Comment by toddharrison** [comment]
It seems that if I add the item-nbt-api-plugin-2.8.0.jar plugin that this error goes away. Will this have any repercussions on Staff++?

**Comment by garagepoort** [comment]
Hey @toddharrison 
You are correct. I will relocate it.
The usage of the nbt API in staff++ is minimal so chances are this won't cause any issues.

**Comment by garagepoort** [comment]
Fixed in latest release
