### ISSUE TITLE
Wont load on 1.17.1

### ISSUE THREAD

**Issue by BirchFluf** [garagepoort/StaffPlusPlus#168]
10.07 18:52:57 [Server] INFO [StaffPlus] Enabling StaffPlus v1.17.6
10.07 18:52:57 [Server] INFO [StaffPlus] Staff++ has been enabled!
10.07 18:52:57 [Server] INFO [StaffPlus] Plugin created by Shortninja continued by Qball - Revisited by Garagepoort
10.07 18:52:57 [Server] INFO [net.shortninja.staffplus.core.be.garagepoort.mcioc.org.reflections.Reflections] Reflections took 106 ms to scan 1 urls, producing 147 keys and 1043 values
10.07 18:52:57 [Server] ERROR Error occurred while enabling StaffPlus v1.17.6 (Is it up to date?)
10.07 18:52:57 [Server] INFO net.shortninja.staffplus.core.be.garagepoort.mcioc.IocException: Mc-Ioc bean exceptions: [Cannot instantiate bean with interface net.shortninja.staffplus.core.be.garagepoort.mcsqlmigrations.SqlConnectionProvider. No classes implementing this interface]
10.07 18:52:57 [Server] INFO at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.instantiateBean(IocContainer.java:171) ~[?:?]
10.07 18:52:57 [Server] INFO at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.buildParams(IocContainer.java:250) ~[?:?]
10.07 18:52:57 [Server] INFO at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.createBean(IocContainer.java:202) ~[?:?]
10.07 18:52:57 [Server] INFO at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.instantiateBean(IocContainer.java:178) ~[?:?]
10.07 18:52:57 [Server] INFO at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.loadIocBeans(IocContainer.java:61) ~[?:?]
10.07 18:52:57 [Server] INFO at net.shortninja.staffplus.core.be.garagepoort.mcioc.IocContainer.init(IocContainer.java:37) ~[?:?]
10.07 18:52:57 [Server] INFO at net.shortninja.staffplus.core.be.garagepoort.mcioc.TubingPlugin.onEnable(TubingPlugin.java:17) ~[?:?]
10.07 18:52:57 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[?:?]
10.07 18:52:57 [Server] INFO at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
10.07 18:52:57 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
10.07 18:52:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
10.07 18:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-97]
10.07 18:52:57 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
10.07 18:52:57 [Server] INFO [StaffPlus] Disabling StaffPlus v1.17.6
10.07 18:52:57 [Server] INFO [StaffPlus] Staff++ is now disabling!
10.07 18:52:57 [Server] INFO [StaffPlus] Staff++ disabled!

**Comment by garagepoort** [comment]
@BirchFluf what is your storage type configured go inside the config.yml?

**Comment by garagepoort** [comment]
Closed due to inactivity
