### ISSUE TITLE
Stuck Vanished

### ISSUE THREAD

**Issue by TheDudesCraps** [garagepoort/StaffPlusPlus#183]
Hi,  I felt like this might be the best place to let you know,  I'm having staff members and OPs get stuck in Vanish mode.  Even after restarts, I've checked the config and followed the wiki when setting it up.  Is there a way to force them back out of vanished upon leaving the server?  it seems that the toggle is not working.  I can provide you with server log if you need.  The only fix for this ive found is to delete the players playerdata which is not good of course.  I did it to myself, but Id much rather not do that to a player.  Any help would be greatly appreciated.

**Comment by garagepoort** [comment]
Hello,

Can you provide me with your plugin version and mc server version?
