### ISSUE TITLE
[Bug] Staff mode allows multiverse inventories to move to other worlds and overwrite

### ISSUE THREAD

**Issue by emerysteele** [garagepoort/StaffPlusPlus#186]
I have multiverse inventories setup so my Creative and Survival worlds have different inventories.

If I am in the Creative world, enable staff mode with /staff, then do `/mv tp Survival`. Multiverse Inventories replaces the staff mode inventory with that world's items, but staff mode is still enabled.
So I do `/staff` to turn staff mode off. Now my inventory get's replaced with the inventory I had loaded in creative and my Survival items are gone.

**Comment by garagepoort** [comment]
Hello @emerysteele 

This is a known issue, multiverse inventories is not yet fully supported.
You should be able to work around the issue by setting the `disable-on-world-change` property to `true` in the `configuration/staffmode/modes.yml` file. This will disable staff mode automatically before switching worlds.

**Comment by emerysteele** [comment]
Perfect, thanks!
