### ISSUE TITLE
Staff can drop items in their "inventory" when switching to staff mode

### ISSUE THREAD

**Issue by gin-iro** [garagepoort/StaffPlusPlus#192]
If you switch to staff mode, you can drop the items in your staff inventory. Is there a way to prevent it?

**Comment by garagepoort** [comment]
Hey @gin-iro 

Yes there is. Inside the modes.yml set `inventory-interaction` to `false`
````
modes:
    default:
        inventory-interaction: false
```

**Comment by gin-iro** [comment]
Thank, you, I somehow missed this.
