### ISSUE TITLE
personnel command

### ISSUE THREAD

**Issue by gin-iro** [garagepoort/StaffPlusPlus#196]
Why does Staff++ not show all staff members who have access to the staff mode when we do /personnel? We have helper, mod, admin, sradmin, owner as ranks for staff members. Helpers are getting trained to become mods. So they have very limited permissions. 

Only admin, sradmin, and owner will come back as a result if I do /personnel. Attached you can see the modes.yml content.
[modes.txt](https://github.com/garagepoort/StaffPlusPlus/files/8010869/modes.txt)

**Comment by garagepoort** [comment]
Hello @gin-iro 

The personnel command shows all players that have the `staff.member` permission.
Make sure all your staff members have this permission

**Comment by gin-iro** [comment]
Thank you so much!
