### ISSUE TITLE
Staffchat discord sync repeating message after reload

### ISSUE THREAD

**Issue by BetoCR16** [garagepoort/StaffPlusPlus#198]
After making a change on the config or templates of the Staff++ Discord Integration plugin, and doing `/staffplusplusdiscord reload`, and with the staffchat sync enabled, the messages coming from discord repeats the same number of times the plugin has been reloaded. However after a restart everything works fine.

- Using Staff++ 1.18.7,  Staff++ Discord Integration 1.16.61 and DiscordSRV 1.24.0

- Message sent from the discord staffchat channel
![image](https://user-images.githubusercontent.com/48104122/153498371-7b380d9f-51dd-486f-8110-e9de3fe7d9a6.png)
- Messages received on minecraft after having executed `/staffplusplusdiscord reload` multiple times.
![image](https://user-images.githubusercontent.com/48104122/153498441-fbf8bd22-f9d0-489f-85be-f1ddcf77c190.png)

**Comment by garagepoort** [comment]
Fixed in release 1.16.63 of the staffplusplus-discord plugin
