### ISSUE TITLE
Feature Request: Prefix Option in config

### ISSUE THREAD

**Issue by coralpapa** [garagepoort/StaffPlusPlus#207]
Having same issue as described in #197 
I have another application that uses a migrations table and causing conflict. 
Second Database isn't an available option for me as provider only allows 1
I was thinking maybe a option in config for prefix would work so users can use a prefix or not

**Comment by garagepoort** [comment]
@coralpapa 
Just released a version.
The migrations table name is now configurable.
`migrations-table-name: 'migrations'`

**Comment by coralpapa** [comment]
Awesome, thank you
