### ISSUE TITLE
Phrase Detection bug?

### ISSUE THREAD

**Issue by coralpapa** [garagepoort/StaffPlusPlus#210]
not sure if this is suppose to be the case.
but a canceled chat event still sends a phrase detection

https://github.com/garagepoort/StaffPlusPlus/blob/512b050abe2b98934c94d049a5e31dd5858dd392/src/main/java/net/shortninja/staffplus/core/domain/chat/PhraseDetectionChatInterceptor.java#L42

**Comment by garagepoort** [comment]
Yeah I think that's a bug. I'll change that

**Comment by coralpapa** [comment]
Thanks, sorry for the different bugs/suggestions wasn't sure if i should just post to a github or a discord support

**Comment by garagepoort** [comment]
No problem I prefer GitHub over discord for bugs and feature requests.

**Comment by coralpapa** [comment]
saw commit 74df6c4 so i'll close this. Thanks again
