### ISSUE TITLE
Feature Request: Addition to blacklist-module

### ISSUE THREAD

**Issue by coralpapa** [garagepoort/StaffPlusPlus#211]
So right now "blacklist-module" gets checked against chat only, can you also add :
signs - SignChangeEvent
anvil - PrepareAnvilEvent

maybe add variable in config to toggle each on/off incase the user doesn't want each checked

was thinking maybe renaming ChatMessageCensoredEvent to just MessageCensoredEvent
and add an Enum to it called Type that would be Chat, Anvil, Sign

Thanks again :-)

**Comment by garagepoort** [comment]
Will be added in next release

**Comment by coralpapa** [comment]
Awesome thank you so much

**Comment by coralpapa** [comment]
Completed with commit c1a6b37

**Comment by coralpapa** [comment]
I forgot a type before with this
book - PlayerEditBookEvent

to check title and pages

**Comment by coralpapa** [comment]
Complete with commit 4164781
Thanks again
