### ISSUE TITLE
Waiting for connection

### ISSUE THREAD

**Issue by max0r4axor** [garagepoort/StaffPlusPlus#216]
The console gets flooded with Waiting for available connection. What is this and how can I get it to stop or fix it right. If it stated what it was waiting for more specifically I could probably figure it out easier.

**Comment by garagepoort** [comment]
Hey @max0r4axor 
This is actually just an info message. This has been removed in the latest release. So if you update that message should no longer be there

**Comment by max0r4axor** [comment]
Thank you for this. I've looked all over for anything that mentioned this and couldn't find any information on it.
