### ISSUE TITLE
Chest inspector bug

### ISSUE THREAD

**Issue by Zoiter7** [garagepoort/StaffPlusPlus#91]
Hello, I want to report a dupe glitch with chest.
I'm using the last release.

Steps:
1. Put yourself in /staff mode and open a chest.
2. Another user open the same chest and place items inside the chest.
3. Close the chest.

**Result**: The item that was placed by the another user will disappear.

**Comment by garagepoort** [comment]
Thanks for your bug report. I will start working on it now. Keep a look out for the next release

**Comment by garagepoort** [comment]
Hi Zoiter7,

The latest release contains the fix. 
- 1.16.19 
- 1.15.14 
- 1.14.13
- 1.13.13

If you encounter any other issues please do not hesitate to contact me
